//
// Created by Yifei Yang on 1/17/22.
//

#ifndef FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H
#define FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H

namespace fpdb::executor::physical {

enum POpType {
  AGGREGATE,
  CACHE_LOAD,
  COLLATE,
  LOCAL_FILE_SCAN,
  REMOTE_FILE_SCAN,
  STORE_FILE_SCAN,
  FILTER,
  GROUP,
  HASH_JOIN_BUILD,
  HASH_JOIN_PROBE,
  NESTED_LOOP_JOIN,
  LIMIT_SORT,
  MERGE,
  PROJECT,
  S3_GET,
  S3_SELECT,
  SHUFFLE,
  SORT,
  SPLIT,
  STORE_SUPER
};

}

#endif //FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_PHYSICAL_POPTYPE_H
