//
// Created by Yifei Yang on 2/26/22.
//

#ifndef FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_SEPARABLEPREPOPEXTRACTOR_H
#define FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_SEPARABLEPREPOPEXTRACTOR_H

namespace fpdb::plan::prephysical::separable {

class SeparablePrePOpExtractor {

};

}


#endif //FPDB_FPDB_PLAN_INCLUDE_FPDB_PLAN_PREPHYSICAL_SEPARABLEPREPOPEXTRACTOR_H
