//
// Created by Yifei Yang on 11/2/21.
//

#ifndef NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_AGGREGATEPREPFUNCTIONTYPE_H
#define NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_AGGREGATEPREPFUNCTIONTYPE_H

namespace normal::plan::prephysical {

enum AggregatePrePFunctionType {
  SUM,
  COUNT,
  MAX,
  MIN,
  AVG
};

}


#endif //NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_AGGREGATEPREPFUNCTIONTYPE_H
