//
// Created by Yifei Yang on 11/2/21.
//

#ifndef NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_FIELDDIRECTION_H
#define NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_FIELDDIRECTION_H

namespace normal::plan::prephysical {

enum FieldDirection {
  ASC,
  DESC
};

}

#endif //NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_FIELDDIRECTION_H
