//
// Created by Yifei Yang on 11/1/21.
//

#ifndef NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_PREPOPTYPE_H
#define NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_PREPOPTYPE_H

namespace normal::plan::prephysical {

enum PrePOpType {
  FILTERABLE_SCAN,
  FILTER,
  HASH_JOIN,
  NESTED_LOOP_JOIN,
  AGGREGATE,
  GROUP,
  SORT,
  LIMIT_SORT,
  PROJECT
};

}

#endif //NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_PREPOPTYPE_H
