//
// Created by Yifei Yang on 1/17/22.
//

#ifndef NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_SORTORDER_H
#define NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_SORTORDER_H

namespace normal::plan::prephysical {

enum SortOrder {
  ASCENDING,
  DESCENDING
};

}

#endif //NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_SORTORDER_H
