//
// Created by Yifei Yang on 11/10/21.
//

#ifndef NORMAL_NORMAL_AWS_INCLUDE_NORMAL_AWS_S3CLIENTTYPE_H
#define NORMAL_NORMAL_AWS_INCLUDE_NORMAL_AWS_S3CLIENTTYPE_H

namespace normal::aws {

enum S3ClientType {
  S3,
  AIRMETTLE,
  MINIO
};

}

#endif //NORMAL_NORMAL_AWS_INCLUDE_NORMAL_AWS_S3CLIENTTYPE_H
