//
// Created by Yifei Yang on 1/17/22.
//

#ifndef NORMAL_NORMAL_EXECUTOR_INCLUDE_NORMAL_EXECUTOR_PHYSICAL_POPTYPE_H
#define NORMAL_NORMAL_EXECUTOR_INCLUDE_NORMAL_EXECUTOR_PHYSICAL_POPTYPE_H

namespace normal::executor::physical {

enum POpType {
  AGGREGATE,
  CACHE_LOAD,
  COLLATE,
  FILE_SCAN,
  FILTER,
  GROUP,
  HASH_JOIN_BUILD,
  HASH_JOIN_PROBE,
  NESTED_LOOP_JOIN,
  LIMIT_SORT,
  MERGE,
  PROJECT,
  S3_GET,
  S3_SELECT,
  SHUFFLE,
  SORT,
  SPLIT
};

}

#endif //NORMAL_NORMAL_EXECUTOR_INCLUDE_NORMAL_EXECUTOR_PHYSICAL_POPTYPE_H
