//
// Created by Yifei Yang on 11/8/21.
//

#ifndef NORMAL_NORMAL_CONNECTOR_INCLUDE_NORMAL_CONNECTOR_CATALOGUEENTRYTYPE_H
#define NORMAL_NORMAL_CONNECTOR_INCLUDE_NORMAL_CONNECTOR_CATALOGUEENTRYTYPE_H

namespace normal::catalogue {

enum CatalogueEntryType {
  LocalFS,
  S3
};

}

#endif //NORMAL_NORMAL_CONNECTOR_INCLUDE_NORMAL_CONNECTOR_CATALOGUEENTRYTYPE_H
