//
// Created by Yifei Yang on 1/15/22.
//

#ifndef NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_AGGREGATEFUNCTIONTYPE_H
#define NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_AGGREGATEFUNCTIONTYPE_H

namespace normal::executor::physical::aggregate {

enum AggregateFunctionType {
  SUM,
  COUNT,
  MIN_MAX,
};

}


#endif //NORMAL_NORMAL_PLAN_INCLUDE_NORMAL_PLAN_PREPHYSICAL_AGGREGATEFUNCTIONTYPE_H
