//
// Created by Yifei Yang on 1/21/22.
//

#ifndef NORMAL_NORMAL_EXECUTOR_INCLUDE_NORMAL_EXECUTOR_MESSAGE_MESSAGETYPE_H
#define NORMAL_NORMAL_EXECUTOR_INCLUDE_NORMAL_EXECUTOR_MESSAGE_MESSAGETYPE_H

namespace normal::executor::message {

enum MessageType {
  START,
  STOP,
  CONNECT,
  COMPLETE,
  ERROR,
  SCAN,
  TUPLE,
  TUPLESET_INDEX,
  LOAD_REQUEST,
  LOAD_RESPONSE,
  STORE_REQUEST,
  WEIGHT_REQUEST,
  CACHE_METRICS
};

}

#endif //NORMAL_NORMAL_EXECUTOR_INCLUDE_NORMAL_EXECUTOR_MESSAGE_MESSAGETYPE_H
